package com.arcdb.jdbc

import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.PrintWriter
import java.net.Socket
import java.sql.*
import java.util.Properties
import java.util.concurrent.Executor

class ArcConnection(
    val host: String,
    val port: Int,
    val database: String
) : Connection {
    val socket: Socket
    val reader: BufferedReader
    val writer: PrintWriter
    private var _isClosed = false

    init {
        socket = Socket(host, port)
        reader = BufferedReader(InputStreamReader(socket.getInputStream()))
        writer = PrintWriter(socket.getOutputStream(), true)

        // Read welcome message
        var line = reader.readLine()
        while (line != null && !line.contains("Ready for queries")) {
             line = reader.readLine()
        }

        // Switch to JSON mode
        writer.println(".mode json")
        reader.readLine() // "Output mode set to JSON"
    }

    override fun createStatement(): Statement {
        return ArcStatement(this)
    }

    override fun prepareStatement(sql: String?): PreparedStatement {
        throw SQLFeatureNotSupportedException("PreparedStatement not supported yet")
    }

    override fun close() {
        if (!_isClosed) {
            writer.println(".quit")
            socket.close()
            _isClosed = true
        }
    }

    // Boilerplate for Connection interface
    override fun <T : Any?> unwrap(iface: Class<T>?): T = throw SQLException("Not implemented")
    override fun isWrapperFor(iface: Class<*>?): Boolean = false
    override fun prepareCall(sql: String?) = throw SQLFeatureNotSupportedException()
    override fun nativeSQL(sql: String?) = sql
    override fun setAutoCommit(autoCommit: Boolean) {} 
    override fun getAutoCommit() = true
    override fun commit() {}
    override fun rollback() {}
    override fun isClosed() = _isClosed
    override fun getMetaData(): DatabaseMetaData = throw SQLFeatureNotSupportedException()
    override fun setReadOnly(readOnly: Boolean) {}
    override fun isReadOnly() = false
    override fun setCatalog(catalog: String?) {}
    override fun getCatalog() = database
    override fun setTransactionIsolation(level: Int) {}
    override fun getTransactionIsolation() = Connection.TRANSACTION_NONE
    override fun getWarnings() = null
    override fun clearWarnings() {}
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int) = createStatement()
    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int) = prepareStatement(sql)
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int) = prepareCall(sql)
    override fun getTypeMap() = emptyMap<String, Class<*>>()
    override fun setTypeMap(map: MutableMap<String, Class<*>>?) {}
    override fun setHoldability(holdability: Int) {}
    override fun getHoldability() = ResultSet.HOLD_CURSORS_OVER_COMMIT
    override fun setSavepoint() = throw SQLFeatureNotSupportedException()
    override fun setSavepoint(name: String?) = throw SQLFeatureNotSupportedException()
    override fun rollback(savepoint: Savepoint?) {}
    override fun releaseSavepoint(savepoint: Savepoint?) {}
    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int) = createStatement()
    override fun prepareStatement(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int) = prepareStatement(sql)
    override fun prepareCall(sql: String?, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int) = prepareCall(sql)
    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int) = prepareStatement(sql)
    override fun prepareStatement(sql: String?, columnIndexes: IntArray?) = prepareStatement(sql)
    override fun prepareStatement(sql: String?, columnNames: Array<out String>?) = prepareStatement(sql)
    override fun createClob() = throw SQLFeatureNotSupportedException()
    override fun createBlob() = throw SQLFeatureNotSupportedException()
    override fun createNClob() = throw SQLFeatureNotSupportedException()
    override fun createSQLXML() = throw SQLFeatureNotSupportedException()
    override fun isValid(timeout: Int) = !isClosed
    override fun setClientInfo(name: String?, value: String?) {}
    override fun setClientInfo(properties: Properties?) {}
    override fun getClientInfo(name: String?) = null
    override fun getClientInfo() = Properties()
    override fun createArrayOf(typeName: String?, elements: Array<out Any>?) = throw SQLFeatureNotSupportedException()
    override fun createStruct(typeName: String?, attributes: Array<out Any>?) = throw SQLFeatureNotSupportedException()
    override fun setSchema(schema: String?) {}
    override fun getSchema() = null
    override fun abort(executor: Executor?) { close() }
    override fun setNetworkTimeout(executor: Executor?, milliseconds: Int) {}
    override fun getNetworkTimeout() = 0
}
